//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Cybersecurity_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public int Id { get; set; }
        public string Idnetifier { get; set; }
        public System.DateTime Date { get; set; }
        public int Score { get; set; }
        public int QuestionNo { get; set; }
        public int TrueQuesNo { get; set; }
        public int FalseQuesNo { get; set; }
        public int ExamTime { get; set; }
    }
}
