//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Cybersecurity_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quiz
    {
        public int id { get; set; }
        public string description { get; set; }
        public string difficulty { get; set; }
        public string choiceA { get; set; }
        public string choiceB { get; set; }
        public string choiceC { get; set; }
        public string choiceD { get; set; }
        public string correct_answer { get; set; }
        public string quizStatus { get; set; }
        public System.DateTime createDate { get; set; }
        public int CategoryId { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
