//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Cybersecurity_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Story
    {
        public int id { get; set; }
        public string name { get; set; }
        public string src { get; set; }
        public string description { get; set; }
        public string storyStatus { get; set; }
        public System.DateTime createDate { get; set; }
    }
}
